import Link from "next/link";
import { Copy, CheckCircle, ExternalLink, Network } from "lucide-react";

export default function BaseLayerPage() {
    return (
        <div className="bg-black text-white min-h-screen pt-12 pb-24">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

                <div className="flex flex-col md:flex-row items-center justify-between mb-16 gap-12">
                    <div className="flex-1">
                        <div className="flex items-center gap-3 mb-6">
                            <div className="bg-blue-600 p-2 rounded-lg">
                                <Network className="text-white w-6 h-6" />
                            </div>
                            <span className="text-blue-400 tracking-wider font-bold">BUILT ON BASE</span>
                        </div>
                        <h1 className="text-5xl md:text-6xl font-bold mb-6">Scalable Layer 2 Infrastructure</h1>
                        <p className="text-xl text-gray-400 leading-relaxed mb-8">
                            We chose Base for its unparalleled speed, low costs, and Ethereum-grade security. Every trade signal generated by WAlphaHunter is anchored on-chain for immutable verification.
                        </p>
                        <div className="flex gap-4">
                            <Link href="https://base.org" className="px-6 py-3 bg-white text-black font-bold rounded-lg hover:bg-gray-200 transition flex items-center gap-2">
                                Learn about Base
                                <ExternalLink className="w-4 h-4" />
                            </Link>
                        </div>
                    </div>

                    {/* Visual/Stats */}
                    <div className="flex-1 bg-gradient-to-br from-blue-900/20 to-black p-8 rounded-3xl border border-blue-500/30 w-full">
                        <div className="grid grid-cols-2 gap-4">
                            <div className="bg-black/50 p-6 rounded-xl border border-white/10">
                                <div className="text-3xl font-bold text-white mb-1">0.5s</div>
                                <div className="text-xs text-gray-400 uppercase">Block Time</div>
                            </div>
                            <div className="bg-black/50 p-6 rounded-xl border border-white/10">
                                <div className="text-3xl font-bold text-green-400 mb-1">$0.01</div>
                                <div className="text-xs text-gray-400 uppercase">Gas Fee</div>
                            </div>
                            <div className="bg-black/50 p-6 rounded-xl border border-white/10 col-span-2">
                                <div className="text-3xl font-bold text-blue-400 mb-1">100%</div>
                                <div className="text-xs text-gray-400 uppercase">EVM Compatible</div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Contract Address */}
                <div className="bg-white/5 border border-white/10 rounded-xl p-6 flex flex-col md:flex-row items-center justify-between gap-4">
                    <div>
                        <h3 className="font-bold text-lg">Verifier Contract (Sepolia)</h3>
                        <p className="text-gray-400 text-sm">Use this address to audit our trade proofs on the block explorer.</p>
                    </div>
                    <div className="flex items-center bg-black rounded-lg px-4 py-3 border border-white/10 font-mono text-sm text-gray-300">
                        <span>0x7f2c...3a29</span>
                        <button className="ml-4 hover:text-white transition">
                            <Copy className="w-4 h-4" />
                        </button>
                    </div>
                </div>

            </div>
        </div>
    );
}
