/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class TitanGuardian {
  constructor()
  /**
   * Calculate Order Flow Imbalance (OFI) from raw Orderbook snapshot.
   * Uses Zero-Copy Buffer for maximum performance.
   * Input: JSON buffer of bids/asks, but parsed manually for speed.
   * For this version, we accept strings for simplicity, but Buffer is supported.
   */
  calculateOfi(bidsJson: string, asksJson: string): number
  /**
   * The "Silicon Guardian" Validation Gate
   * Validates AI intent against Datalog risk invariants.
   * Returns: { allowed: boolean, reason: string }
   */
  validateIntent(side: string, size: number, vol: number, ofi: number, trend: string, adx: number, rsi: number, positionCount: number): string
  updatePosition(symbol: string, quantity: number, price: number): void
  getPortfolioState(): string
}
