
import os
import chromadb
from chromadb.config import Settings
from flask import Flask, request, jsonify
import logging

# Configure Logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("TitanMemory")

app = Flask(__name__)

# Initialize ChromaDB (Persistent)
db_path = os.path.join(os.getcwd(), "titan_memory_db")
chroma_client = chromadb.PersistentClient(path=db_path)

# Create/Get Collection
collection = chroma_client.get_or_create_collection(name="titan_trading_memory")

@app.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "active", "memories": collection.count()})

@app.route('/remember', methods=['POST'])
def remember():
    """Store a trade outcome (Win/Loss) with its vector context"""
    try:
        data = request.json
        # Format: { "id": "uuid", "embedding": [vector], "metadata": { "result": "WIN", "symbol": "BTC", ... } }
        
        collection.add(
            ids=[data['id']],
            embeddings=[data['embedding']], # Can be generated by DeepSeek or raw features
            metadatas=[data['metadata']],
            documents=[data.get('document', '')]
        )
        logger.info(f"🧠 Remembered trade {data['id']}")
        return jsonify({"success": True}), 200
    except Exception as e:
        logger.error(f"Error remembering: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/recall', methods=['POST'])
def recall():
    """Find similar past market situations"""
    try:
        data = request.json
        # Format: { "query_embedding": [vector], "n_results": 5 }
        
        results = collection.query(
            query_embeddings=[data['query_embedding']],
            n_results=data.get('n_results', 5)
        )
        
        return jsonify({"results": results}), 200
    except Exception as e:
        logger.error(f"Error recalling: {e}")
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    logger.info("🧠 Titan V5 Memory Server Starting on Port 5000...")
    app.run(host='0.0.0.0', port=5000)
